{{- if .Values.pdb.backend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "logiq.fullname" . }}-backend
  labels:
    {{- include "logiq.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.pdb.backend.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "logiq.name" . }}
      app.kubernetes.io/component: backend
{{- end }}
---
{{- if .Values.pdb.frontend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "logiq.fullname" . }}-frontend
  labels:
    {{- include "logiq.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: {{ .Values.pdb.frontend.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "logiq.name" . }}
      app.kubernetes.io/component: frontend
{{- end }}
